# Generated by Django 5.2.3 on 2025-06-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_image_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True),
        ),
    ]
