# Generated by Django 5.2.3 on 2025-06-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
